[versions]
agp = "8.11.0"
kotlin = "2.1.21"
ksp = "2.1.21-2.0.2"
composeBom = "2025.06.01"
composeCompiler = "2.2.0" # Matches the hardcoded version
firebaseBom = "33.16.0"
hilt = "2.56.2" # Using a consistent, recent version
openapiGenerator = "7.6.0"
googleServices = "4.4.3"
firebaseCrashlytics = "3.0.4" # Matches the hardcoded version

firebasePerf = "1.4.2"
coreKtx = "1.16.0"
appcompat = "1.7.1"
lifecycle = "2.9.1"
activityCompose = "1.10.1"
navigation = "2.9.0"
room = "2.7.2"
workManager = "2.10.2"
datastore = "1.1.7"
securityCrypto = "1.1.0-beta01"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
kotlinxCoroutinesTest = "1.10.2"
mockk = "1.13.10"
androidxTestExtJunit = "1.2.1"
espressoCore = "3.6.1"
coilCompose = "2.7.0"
accompanistPermissions = "0.37.3"
retrofit = "3.0.0"
okhttp = "4.12.0"
retrofitKotlinxSerializationConverter = "1.0.0"
kotlinxSerializationJson = "1.9.0"
kotlinxDatetime = "0.7.0"
guava = "33.4.8-android"

[libraries]
# Core & Lifecycle
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version = "1.16.0" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.1" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version = "1.10.1" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest", version = "1.8.3" }

# Navigation (Compose only)
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Hilt & DI
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Room (Persistence)
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Network (Retrofit + Kotlinx Serialization)
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
jakewharton-retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }

# Serialization (The ONE true choice)
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
jetbrains-kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version = "33.16.0" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "22.5.0" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version = "19.4.4" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx", version = "21.0.5" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx", version = "23.2.1" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version = "25.1.4" }

# Other AndroidX
androidx-security-crypto-ktx = { group = "androidx.security", name = "security-crypto-ktx", version.ref = "securityCrypto" }
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# UI Libraries
coil-compose = { group = "io.coil-kt", name = "coil-compose", version = "2.7.0" }
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version = "0.37.3" }

# Utilities
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# Testing
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
test-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidTest-androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidTest-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

[plugins]
agp = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
openapi-generator = { id = "org.openapitools.generator", version.ref = "openapiGenerator" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlytics" }
firebase-perf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerf" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "composeCompiler" }
