# This file is used to declare all dependency versions and plugin versions centrally.
# Read more: https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog-format

[versions]
agp = "8.4.1"
kotlin = "2.0.0"
kspVersion = "2.0.0-1.0.21" # Renamed from ksp
openapiGeneratorVersion = "7.6.0" # Renamed from openapiGenerator
hiltVersion = "2.56.2" # Renamed from hilt, User-specified advanced version
room = "2.7.0" # User-specified advanced version
windowExtensions = "1.2.0"

# Plugin-specific versions (if not covered by broader categories like kotlin, agp, hiltVersion)
googleServicesPluginVersion = "4.4.2"
firebaseCrashlyticsPluginVersion = "2.9.9"
firebasePerfPluginVersion = "1.4.2"

# Library versions
composeBom = "2024.05.00"
firebaseBom = "33.15.0"
cmake = "3.22.1"
ndk = "26.2.11394342"
coreKtx = "1.13.1"
appcompat = "1.7.0"
lifecycle = "2.8.4"
activityCompose = "1.9.1" # May need update for Kotlin 2.0 / Compose (using BOM)
navigation = "2.7.7"
workManager = "2.9.0"
datastore = "1.1.1"
securityCrypto = "1.1.0-alpha06"
multidex = "2.0.1"
hiltNavigationCompose = "1.2.0"
junit = "4.13.2"
kotlinxCoroutinesTest = "1.8.1"
androidxArchCoreTesting = "2.2.0"
mockk = "1.13.10"
androidxTestExtJunit = "1.2.1"
espressoCore = "3.6.1"
coilCompose = "2.6.0"
accompanistPermissions = "0.34.0"
accompanistSystemUIController = "0.34.0"
moshiKotlin = "1.15.1"
moshiAdapters = "1.15.1"
gson = "2.10.1"
retrofit = "2.11.0"
okhttp = "4.12.0"
retrofitKotlinxSerializationConverter = "1.0.0"
kotlinxSerializationJson = "1.6.3"
kotlinxDatetime = "0.5.0"
guava = "33.2.0-android"


[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

# Compose BOM and dependencies
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material = { group = "androidx.compose.material", name = "material" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-runtime-livedata = { group = "androidx.compose.runtime", name = "runtime-livedata" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-animation-tooling = { group = "androidx.compose.animation", name = "animation-tooling", version = "1.6.7" } # Example of a direct version

# Navigation
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigation" }

# Hilt & Dagger
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hiltVersion" } # Updated ref
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hiltVersion" } # Updated ref
hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "hiltNavigationCompose" }

# Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }

# Network
squareup-retrofit2-retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
squareup-okhttp3-okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
squareup-okhttp3-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
jakewharton-retrofit2-kotlinx-serialization-converter = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "retrofitKotlinxSerializationConverter" }

# Serialization
jetbrains-kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
jetbrains-kotlinx-datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "kotlinxDatetime" }

# Firebase BOM and dependencies
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics-ktx = { group = "com.google.firebase", name = "firebase-analytics-ktx" }
firebase-crashlytics-ktx = { group = "com.google.firebase", name = "firebase-crashlytics-ktx" }
firebase-perf-ktx = { group = "com.google.firebase", name = "firebase-perf-ktx" }
firebase-auth-ktx = { group = "com.google.firebase", name = "firebase-auth-ktx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx" }

# Security
androidx-security-crypto-ktx = { group = "androidx.security", name = "security-crypto-ktx", version.ref = "securityCrypto" }

# WorkManager
androidx-work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "workManager" }

# DataStore
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Image Loading
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coilCompose" }

# Permissions & System UI (Accompanist)
google-accompanist-permissions = { group = "com.google.accompanist", name = "accompanist-permissions", version.ref = "accompanistPermissions" }
google-accompanist-systemuicontroller = { group = "com.google.accompanist", name = "accompanist-systemuicontroller", version.ref = "accompanistSystemUIController" }

# Other JSON/Serialization libs
squareup-moshi-kotlin = { group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshiKotlin" }
squareup-moshi-adapters = { group = "com.squareup.moshi", name = "moshi-adapters", version.ref = "moshiAdapters" }
google-code-gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# Guava for ListenableFuture
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }

# AndroidX Window Extensions
androidx-window-extensions = { group = "androidx.window", name = "window-extensions", version.ref = "windowExtensions" }

# Testing
test-junit = { group = "junit", name = "junit", version.ref = "junit" }
test-kotlinx-coroutines = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
test-androidx-arch-core = { group = "androidx.arch.core", name = "core-testing", version.ref = "androidxArchCoreTesting" }
test-mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
androidTest-androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidTest-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }


[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hiltVersion" } # Uses hiltVersion
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" } # Uses kspVersion
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
openapitoolsGenerator = { id = "org.openapitools.generator", version.ref = "openapiGeneratorVersion" } # Uses openapiGeneratorVersion
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServicesPluginVersion" }
firebaseCrashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebaseCrashlyticsPluginVersion" }
firebasePerf = { id = "com.google.firebase.firebase-perf", version.ref = "firebasePerfPluginVersion" }
# Jetpack Compose plugin is not explicitly added here as we rely on Kotlin 2.0 + buildFeatures.compose = true

# To use a plugin from this catalog, in your module's build.gradle.kts:
# plugins {
#   alias(libs.plugins.androidApplication)
# }
