name: "Build & Test Production"

on:
  push:
    branches: [main, master, production]
  pull_request:
    branches: [main, master, production]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      JAVA_OPTS: "-Xmx4g"
      GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.jvmargs='-Xmx4g'"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Download Android SDK tools
        uses: android-actions/setup-android@v3

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run detekt (code quality)
        run: ./gradlew detekt

      - name: Run lint (Android Lint)
        run: ./gradlew lint

      - name: Run unit tests
        run: ./gradlew test

      - name: Build APK (Release)
        run: ./gradlew assembleRelease

      - name: Build AAB (Bundle)
        run: ./gradlew bundleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/*.apk

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: app/build/outputs/bundle/release/*.aab

      - name: Generate code coverage report (optional)
        run: ./gradlew jacocoTestReport || true

      - name: Upload code coverage report (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: app/build/reports/jacoco/test/html

      - name: Clean up (optional)
        run: ./gradlew clean
