name: Ensure Write Access, Generate API, and CMake Build

on:
  workflow_dispatch:
  push:
    branches:
      - fix/hilt-ksp-errors

jobs:
  setup-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Ensure all folders are writeable
        run: chmod -R u+w .

      - name: Set up JDK for Gradle (if using Java/Kotlin)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Generate API contract
        # Replace this command with your actual generation task:
        run: ./gradlew generateOpenApiContract

      - name: Show OpenAPI file(s) in api-spec folder
        run: ls -l api-spec

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Run CMake (refresh/generate)
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
