name: Manual Build and API Generation

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set write permissions for all folders
        run: chmod -R u+w .

      - name: Create local.properties for Android build
        run: echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Ensure gradlew is executable
        run: chmod +x ./gradlew

      - name: Generate API contract
        run: ./gradlew :app:openApiGenerate

      - name: List API spec files
        run: ls -l api-spec || echo "aura-auraframefx-api.yml"

      - name: Run Gradle build
        run: ./gradlew build

      - name: Set up CMake
        uses: jwlawson/actions-setup-cmake@v2

      - name: Run CMake
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
