name: Manual APK Build

on:
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Debug APK (Manual)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build APK (assembleDebug)
        run: ./gradlew :app:assembleDebug --stacktrace | tee build-output.log

      - name: Upload ALL APKs (any variant)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: all-apks
          path: |
            app/build/outputs/apk/**/*.apk
            app/build/outputs/apk/*/*.apk
            app/build/outputs/**/apk/**/*.apk
            app/build/outputs

      - name: Upload Build Log
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-output-log
          path: build-output.log
